name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_ios:
    name: Build iOS
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./mental_health_app
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - run: flutter build ios --release --no-codesign

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: "**/build/ios/iphoneos/Runner.app"
